"""CLI entrypoints for local Ouroboros setup."""

from __future__ import annotations

from pathlib import Path

import click

from .config import Settings


def _display_path(path: Path) -> str:
    path_str = path.as_posix()
    if path.is_absolute():
        return path_str
    return f"./{path_str.removeprefix('./')}"


@click.group()
def cli() -> None:
    """Ouroboros command line tools."""


@cli.command("init")
def init_command() -> None:
    """Create local .env files for first-run setup."""
    env_path = Path(".env")
    env_example_path = Path(".env.example")
    if env_path.exists():
        click.echo(".env exists; not overwriting")
        return

    defaults = Settings()
    default_data_dir = _display_path(defaults.data_dir)
    default_db_url = defaults.db_url_resolved()

    data_dir = click.prompt("Data directory", default=default_data_dir, show_default=True)
    db_url = click.prompt("Database URL", default=default_db_url, show_default=True)

    lines = [
        "# Generated by `ouroboros init`",
        f"OUROBOROS_DATA_DIR={data_dir}",
        f"OUROBOROS_DB_URL={db_url}",
        "",
    ]
    env_contents = "\n".join(lines)
    env_path.write_text(env_contents, encoding="utf-8")
    env_example_path.write_text(env_contents, encoding="utf-8")
    click.echo("Wrote .env and .env.example")


if __name__ == "__main__":
    cli()
